[package]
name = "platform"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0"
arch = { path = "../arch" }
config = { path = "../config" }
ksync = { path = "../ksync" }
spin = "0"

preprint = "0.1.0"
fdt = { git = "https://github.com/repnop/fdt" }

[features]
qemu_riscv = []
vf2 = []
hifive = []
smp = []